name: Build macOS .app

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build .app
        run: pyinstaller --onefile --windowed GreenCloud.py

      - name: Upload .app artifact
        uses: actions/upload-artifact@v4
        with:
          name: GreenCloud-app
          path: dist/GreenCloud.app
